name: Open a PR to OCI Factory

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    uses: canonical/observability/.github/workflows/rock-release-oci-factory.yaml@v1
    secrets: inherit
    with:
      rock-name: xk6
